### ISSUE TITLE
Cannot find catch.hpp

### ISSUE THREAD

**Issue by tslator** [FreeYourSoul/FSeam#2]
**Compilation Error**
While following the directions on the readme, build of FSeam fails with the following error:
`In file included from /home/tim/fseaminvestigation/FSeam/build/test/FSeamMockData.hpp:11:0,
                 from /home/tim/fseaminvestigation/FSeam/build/test/FreeFunctionClass.fseam.cc:8:
/home/tim/fseaminvestigation/FSeam/test/../FSeam/FSeam/FSeam.hpp:32:10: fatal error: catch.hpp: No such file or directory
 #include <catch.hpp>
          ^~~~~~~~~~~
`

Catch builds correctly and catch.hpp can be found in the expected locations:
`./home/tim/fseaminvestigation/Catch2/include/catch.hpp
./home/tim/fseaminvestigation/Catch2/single_include/catch2/catch.hpp
./usr/local/include/catch2/catch.hpp`

**To Reproduce**
Clone master of Catch2 and FSeam
Follow instructions provided in readme.
**Note: -H. parameter in Catch2 build does not work (cmake version 3.10.02)**

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.2 LTS

**Comment by FreeYourSoul** [comment]
I installed Catch2 manually directly at the root of /usr/include, which is an error as the official installation of catch2 creates a folder catch2/catch.hpp.
It is fixed (will require a new installation of fseam though as FSeam header file has to be updated to includes
#include <catch2/catch.hpp>

It is strange that travis didn't find out this issue though, could you re-try?
